Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 400

Metrics/BlockLength:
  Max: 100

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'